version: '3.7'
services:
    code_inventory_frontend-app:
        image: vinlab/vc-inlab-cit-frontend:latest
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - JHIPSTER_SLEEP=0
        ports:
            - 10100:8080
    code_inventory_backend-postgresql:
        image: vinlab/vc-inlab-cit-postgres:1.0.0
        volumes:
            - '~/.veracode/code-inventory/data/postgresql/:/var/lib/postgresql/data/'
        ports:
            - 5432:5432
    code_inventory_backend-grafana:
        image: vinlab/vc-inlab-cit-grafana:1.0.1
        volumes:
            - ~/.veracode/code-inventory/grafana/data:/var/lib/grafana
        user: "104"
        environment:
            - GF_PATHS_CONFIG=/etc/grafana/grafana-config.ini
        ports:
            - 10110:3000
        secrets:
            - code-inventory-db-grafana-password
secrets:
    code-inventory-master-password:
        external: true
    code-inventory-db-backend-password:
        external: true
    code-inventory-db-postgres-password:
        external: true
    code-inventory-db-grafana-password:
        external: true
    code-inventory-mail-config:
        external: true

    