version: '2'
services:
    code_inventory_backend-app:
        image: vinlab/code-inventory-backend:${TAG}
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://code_inventory_backend-postgresql:5432/code_inventory_backend'
            - JHIPSTER_SLEEP=0
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 10101:10101
        volumes:
            - ~/.veracode/code-inventory/jobs:/var/jobs
            - ~/.veracode/code-inventory/code:/var/code
    code_inventory_backend-postgresql:
        image: vinlab/vc-inlab-cit-backend-postgres-image:${TAG}
        volumes:
            - '~/.veracode/code-inventory/data/postgresql/:/var/lib/postgresql/data/'
        environment:
            - POSTGRES_PASSWORD=Smart-bananas-silly-nuts-57
            - POSTGRES_DB=code_inventory_backend
            - PGPASSWORD=Fog-city-mamba-27
        ports:
            - 5432:5432
    code_inventory_backend-grafana:
        image: vinlab/vc-inlab-cit-backend-grafana-image:${TAG}
        container_name: 'docker_code_inventory_backend-grafana_1' 
        volumes:
            - ~/.veracode/code-inventory/grafana/data:/var/lib/grafana
        user: "104"
        environment:
            - GF_PATHS_CONFIG=/etc/grafana/grafana-config.ini
        ports:
            - 10110:3000
            