version: '3.7'
services:
    code_inventory_backend-postgresql:
        image: vinlab/vc-inlab-cit-postgres:1.0.0
        volumes:
            - '~/.veracode/code-inventory/data/postgresql/:/var/lib/postgresql/data/'
        ports:
            - 10111:10111
    code_inventory_backend-grafana:
        image: vinlab/vc-inlab-cit-grafana:1.0.1
        # 'container_name' is not supported by docker stack deploy
        #container_name: 'docker_code_inventory_backend-grafana_1'
        volumes:
            - ~/.veracode/code-inventory/grafana/data:/var/lib/grafana
        user: "104"
        environment:
            - GF_PATHS_CONFIG=/etc/grafana/grafana-config.ini
        ports:
            - 10110:3000
        secrets:
            - code-inventory-db-grafana-password
secrets:
    code-inventory-master-password:
        external: true
    code-inventory-db-backend-password:
        external: true
    code-inventory-db-postgres-password:
        external: true
    code-inventory-db-grafana-password:
        external: true
